services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - CONFIG_PATH=/code/Cargo.toml
    volumes:
      - ./config:/app/config
